apply_requirements:
  checks:
    approved:
      enabled: false
      count: 1
    merge_conflicts:
      enabled: true
    status_checks:
      enabled: true
      ignore_matching: []
  create_pending_apply_check: true
automerge:
  enabled: false
  delete_branch: false
checkout_strategy: merge
when_modified:
  file_patterns: ["**/*.tf", "**/*.tfvars"]
  autoplan: true
  autoplan_draft_pr: true
  autoapply: false
cost_estimation:
  enabled: false
  provider: infracost
  currency: USD