apply_requirements:
  checks:
    approved:
      enabled: false
      count: 1
    merge_conflicts:
      enabled: true
    status_checks:
      enabled: false
      ignore_matching: []
  create_pending_apply_check: false
automerge:
  enabled: true
  delete_branch: true
checkout_strategy: merge
when_modified:
  file_patterns: ["**/*.tf", "**/*.tfvars"]
  autoplan: true
  autoplan_draft_pr: true
  autoapply: false
cost_estimation:
  enabled: false
  provider: infracost
  currency: USD
dirs:
  'environments/prod/**/*.tf':
    tags: [prod]
  'environments/dev/**/*.tf':
    tags: [dev]
workflows:
  - tag_query: "prod"
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply
  - tag_query: "dev"
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      # - type: apply