name: Actions Workflow

on: 
  push:
    branches:
      - master

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: List files
        run: |
          pwd
          ls
      
      - name: List Environment Variables of github
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE    
          echo "${{ github.token }}"
      
      # - name: Simple JS Action
      #   id: greet
      #   uses: actions/hello-world-javascript-action@v1
      #   with: 
      #     who-to-greet: Thea mae
      
      # - name: Log Greeting Time
      #   run: echo "${{ steps.greet.outputs.time }}"    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        PM_VERSION=`cat version | sed -e 's/\-/./g'`
        TAG="v$PM_VERSION"
        git tag $TAG
    - name: Commit files
      run: |
        git config --local user.email "kevinsoriano2828@gmail.com"
        git config --local user.name "john-kevin"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true  