name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create Tag
        run: |
          git tag -a v1.0.1 -m "Fix pipeline"
          git push origin v1.0.1
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Thea mae
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"    