name: Ouput information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}" # more on https://docs.github.com/en/actions/learn-github-actions/contexts